### ISSUE TITLE
Flutter sample's text input loses focus after submission

### ISSUE THREAD

**Issue by loic-sharma** [google/generative-ai-dart#60]
Repro steps:

1. Run the Flutter sample.
2. Type text and press `Enter`

Expected result: the text input stays focused after the response is shown
Actual result: the text input loses focus after the response is shown

**Comment by devoncarew** [comment]
Thanks for the report! cc @johnpryan (who wrote the sample) and @khanhnwin (who's contributed fixes to it)

**Comment by johnpryan** [comment]
@loic-sharma I think this is the right way to fix it, please take a look and let me know what you think: https://github.com/google/generative-ai-dart/pull/61
