### ISSUE TITLE
`generateContent` doesn't use provided http client

### ISSUE THREAD

**Issue by RobertOdrowaz** [google/generative-ai-dart#64]
When creating `GenerativeModel` we can provide a custom http client using the `httpClient` argument. This http client is used when `generateContentStream` is called but is not used by `generateContent`.

The issue lies in the implementation of `HttpApiClient`. The `streamRequest` method used by `generateContentStream` correctly uses `_httpClient` if provided. 
```
final response = _httpClient == null
    ? await request.send()
    : await _httpClient.send(request);
```

However, `makeRequest` used by `generateContent` does not. It always uses the global `post` method from `http` package.  
```
final response = await http.post(
  uri,
  headers: {
    'x-goog-api-key': _apiKey,
    'x-goog-api-client': clientName,
    'Content-Type': 'application/json',
  },
  body: _utf8Json.encode(body),
);
```

**Comment by devoncarew** [comment]
Yup, I see the issue here:

https://github.com/google/generative-ai-dart/blob/main/pkgs/google_generative_ai/lib/src/client.dart#L44

Thanks for the report! Contributions here are welcome.

/cc @brianquinlan

**Comment by brianquinlan** [comment]
Oops, I didn't notice that one. I'll create a PR to fix.

**Comment by brianquinlan** [comment]
Fixed in https://github.com/google/generative-ai-dart/pull/65
