### ISSUE TITLE
Not available in Canada 

### ISSUE THREAD

**Issue by igbokwenu** [google/generative-ai-dart#79]
Despite the post showing that Gemini is now available in Canada, our app users in Canada are getting an Instance of "UnsupportedUserLocation" error with the google_generative_ai API. Would be helpful to get a feedback on this.
![Screenshot_20240218-142323_Gallery](https://github.com/google/generative-ai-dart/assets/68666335/b4c97399-d5e4-42f8-ad09-85646d277d65)

https://blog.google/intl/en-ca/products/explore-get-answers/gemini-ca/amp/

**Comment by anderdobo** [comment]
The blog post is referring to Gemini the conversational AI (formally named Bard) at https://gemini.google.com/.
This package is for accessing the Gemini API, and the available regions are listed at https://ai.google.dev/available_regions#available_regions
Canada is not yet supported for access to the Gemini API.
