### ISSUE TITLE
Vertex AI support

### ISSUE THREAD

**Issue by RobertOdrowaz** [google/generative-ai-dart#83]
It would be great if this package supported using it with Vertex AI. Currently, it's impossible to use it in the EU without hacks to make it work with Vertex AI.

I know there are some differences between the API, probably there are a few more:
1. Different URL
2. Different authorization header
3. Slight difference in `citationMetadata`. One has a `citations` field the other has `citationSources`. Also, the citation model itself is a bit different.

**Comment by anderdobo** [comment]
Thanks. The request for Vertex AI support is note. However, this specific package is for the Google AI Gemini API only. Vertex AI would be handled separately.
